### ISSUE TITLE
Adding "Patterns/Anti-patterns" lint rules from official Angular repo

### ISSUE THREAD

**Issue by fabm22** [Gillespie59/eslint-plugin-angular#133]
As an **improvement**, it would be great to also check some Best-patterns/Anti-patterns from official Angular repo, particurarly the Anti-patterns which shouldn't be too hard to check. 
( https://github.com/angular/angular.js/wiki/Anti-Patterns )

Also, potential convergence with John Papa's angular-styleguide request I made (wait and see). Link : https://github.com/johnpapa/angular-styleguide/issues/447 

---- 

<s>1. Don't wrap element inside of $(). All AngularJS elements are already jq-objects</s> covered by `no-jquery-angularelement`
<s>2. Don't do if (!$scope.$$phase) $scope.$apply(), it means your $scope.$apply() isn't high enough in the call stack.</s> covered by `no-private-call`
<s>3. Don't use jQuery to generate templates or DOM</s> partially covered by `angularelement`
<s>4. Don't create a new plugin without trying to discover, fork and pull request existing plugins first</s> no way to cover this by static code analysis
5. Don't use a scalar variable (null is scalar) as a model within an isolate scope (such as ng-if). (Example: http://embed.plnkr.co/qRhLfw/preview)

**Comment by tilmanpotthof** [comment]
+1

**Comment by tilmanpotthof** [comment]
Here the 5 rules from the documentation.

1. Don't wrap element inside of $(). All AngularJS elements are already jq-objects
2. Don't do if (!$scope.$$phase) $scope.$apply(), it means your $scope.$apply() isn't high enough in the call stack.
3. Don't use jQuery to generate templates or DOM
4. Don't create a new plugin without trying to discover, fork and pull request existing plugins first
5. Don't use a scalar variable (null is scalar) as a model within an isolate scope (such as ng-if). (Example: http://embed.plnkr.co/qRhLfw/preview)

**Comment by tilmanpotthof** [comment]
Rule 1 is partially covered by the 'angularelement' rule, but it the report gives a wrong hint for this use case ('You should use angular.element instead of the jQuery $ object')
Rule 2 is already covered by 'no-private-call' which forbids the usage of any $$-prefixed property.
Rule 3 is partially covered like rule 1, but a detection for DOM manipulation methods like append, prepend etc. might be better
Rule 4 - cannot be covered by a linter.
Rule 5 - the detection for a usage in isolate scope directives can be difficult to implement. A general restriction of scalar values on a scope might be a useful but more restrictive alternative. On the other side such a rule could only cover direct scalar value assignments. Scalar return values from a function would not be covered.

**Comment by tilmanpotthof** [comment]
3 of 5 rules are already covered and 1 can not be covered. I opened an issue for the last rule (#315) and close this issue.

@fabm22 Hope that's ok for you.
