### ISSUE TITLE
No reference to $digest deprecation

### ISSUE THREAD

**Issue by cafesanu** [Gillespie59/eslint-plugin-angular#294]
Hi,
About the `angular/no-digest`.I tried to find any link regarding the deprecation of $digest in favor of $apply with no luck. If there is no such a notice from the angular team, Is there a reason this should be a rule?

Thanks! awesome job with this eslint plugin!

**Comment by tilmanpotthof** [comment]
The deprecation notice is misleading. The rule itself is deprecated, not the usage $digest.

As far as I know there is no argument to use $apply instead of $digest. There is also no such mention in the styleguide by john papa and todd motto even recommends the usage of $digest for performance reasons (if possible) https://github.com/toddmotto/angularjs-styleguide#performance.

If you want to enforce the use of one or the other way ($apply, $digest), you can use the [watchers-execution](https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/watchers-execution.md).

I open another issue #295 to improve the docs and close this one.

**Comment by tilmanpotthof** [comment]
... and thanks for the feedback! :-)

**Comment by cafesanu** [comment]
:+1:
