### ISSUE TITLE
How we can use this for Angular2. Its not clear.

### ISSUE THREAD

**Issue by vasuneet** [Gillespie59/eslint-plugin-angular#487]
Hi Team,

In documentation , no where you mentioned how we can use this for Angular 2/4 project.
Please elaborate.

Regards
Vasuneet Arya

**Comment by vasuneet** [comment]
Any update on this ?

**Comment by Gillespie59** [comment]
We can use it only if we have one day specific rules for Angular2. In the README, I only explained that its possible to detect the version of the framwork, and use it in a ESLint rule. 
Unfortunately, we do not have any rules for the moment. You should have a look to the Codelyzer project, a plugin for the TSLint linter

**Comment by mderazon** [comment]
Any idea on how to use this for **Angular 1** projects running in TS ?
The [Angular upgrade guide](https://angular.io/guide/upgrade#migrating-to-typescript) recommends switching to Typescript as soon as possible but at the same time recommends using a linter for John Papa styleguide. So switching to TS leaves us with no way to lint the project anymore.

Any advice on how to solve this issue ?

**Comment by tsvetan-ganev** [comment]
My team and me are facing the same problem as @mderazon - we have to migrate a huge codebase to TypeScript and to AngularJS components (from controllers/templates). While we see the clear benefits of using TypeScript, the huge downside is that we can no longer use this ESLint plugin, which also helps us during the migration process to the new AngularJS patterns. I will be really grateful if somebody can share a workaround which will allow us to use this plugin alongside TypeScript.

**Comment by pablovegaimexhs** [comment]
HI everybody,

I have a project with Angular version 7 (Using typescript). I want to know if there is an upgrade in order to use this plugin with Angular version 7. I also see that eslint now is working with typescript since **tslint** is deprecated:
https://palantir.github.io/tslint/
![image](https://user-images.githubusercontent.com/67170659/108539838-7fdd0800-72ae-11eb-9094-43e598656d0e.png)

**Comment by pablovegaimexhs** [comment]
Hi everybody,

I want to know if there is a way that this plugin works together with the new [typescript-slint plugin](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin).  Since the [tslint ](https://palantir.github.io/tslint/) has been deprecated 

![image](https://user-images.githubusercontent.com/67170659/108548328-b10f0580-72b9-11eb-85ad-07b7eb9ab5a7.png)

If it is not possible I want to know if there is a way this plugin works for non-AngularJS scenarios (Angular version 7 using typescript) .

**Comment by EmmanuelDemey** [comment]
This plugin only work AngularJS application. We do not have any rules dedicated to Angular application.
